### ISSUE TITLE
[Bug] No module named "wandb2numpy.export"

### ISSUE THREAD

**Issue by sebimarkgraf** [ALRhub/wandb2numpy#3]
Hey,

Importing the module leads to 
``` bash
>>> import wandb2numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sebbo/Projekte/wandb2numpytest/venv/lib/python3.9/site-packages/wandb2numpy/__init__.py", line 1, in <module>
    from .export import export_data
ModuleNotFoundError: No module named 'wandb2numpy.export'
```

Seems to be a missing export file in the package.

**Comment by KoljaBauer** [comment]
Hi Sebastian,

sorry for that. Before the latest commit I changed the project structure and forgot to include this file. It should now work with the commit that I just pushed.
